=== mobilis/Emulation/GWTEmulationServer/src/script-utils/XMLEmulationScript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" xmlns:tns="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" elementFormDefault="qualified">
	
	<complexType name="parameterType">
		<sequence>
			<choice maxOccurs="unbounded">
				<element name="int" type="int"/>
				<element name="string" type="string"/>
				<element name="boolean" type="boolean"/>
				<element name="double" type="double"/>
			</choice>
		</sequence>
	</complexType>
	
	<element name="abstractInstance" abstract="true" substitutionGroup="tns:setupCommand" type="tns:abstractInstanceType"/>
	
	<complexType name="abstractInstanceType">
		<complexContent>
			<extension base="tns:setupCommandType">
				<attribute name="varName" type="NCName" use="required"/>
				<attribute name="appNS" type="string" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="instance" substitutionGroup="tns:abstractInstance" type="tns:instanceType"/>
	
	<complexType name="instanceType">
		<complexContent>
			<extension base="tns:abstractInstanceType">
				<attribute name="instanceId" type="int" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="instanceGroup" substitutionGroup="tns:abstractInstance" type="tns:instanceGroupType"/>
	
	<complexType name="instanceGroupType">
		<complexContent>
			<extension base="tns:abstractInstanceType">
				<attribute name="instanceCount" type="int" use="required"/>
				<attribute name="firstInstanceId" type="int" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="for" substitutionGroup="tns:structure" type="tns:forType"/>
	
	<complexType name="forType">
		<complexContent>
			<extension base="tns:structureType">
				<attribute name="times" type="int" use="required"/>
			</extension>		
		</complexContent>
	</complexType>
	
	<element name="block" substitutionGroup="tns:structure" type="tns:blockType"/>
	
	<complexType name="blockType">
		<complexContent>
			<extension base="tns:structureType"/>
		</complexContent>
	</complexType>
	
	<element name="structure" abstract="true" substitutionGroup="tns:command" type="tns:structureType"/>
	
	<complexType name="structureType">
		<complexContent>
			<extension base="tns:commandType">
				<sequence>
					<element ref="tns:command" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="appCommand" substitutionGroup="tns:atomicCommand" type="tns:appCommandType"/>
	
	<complexType name="appCommandType">
		<complexContent>
			<extension base="tns:atomicCommandType">
				<sequence>
					<element name="parameter" type="tns:parameterType" minOccurs="0" maxOccurs="1"/>
				</sequence>
	            <attribute name="instance" type="NCName" use="required"/>
	            <attribute name="methodName" type="string" use="required"/>
	            <attribute name="async" type="boolean" use="optional" default="false"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="setupMethods" abstract="true" substitutionGroup="tns:setupCommand" type="tns:setupMethodsType"/>
	
	<complexType name="setupMethodsType">
		<complexContent>
			<extension base="tns:setupCommandType">
				<attribute name="instance" type="NCName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="start" substitutionGroup="tns:setupMethods" type="tns:startType"/>
	
	<complexType name="startType">
		<complexContent>
			<extension base="tns:setupMethodsType">
				<sequence>
					<element name="parameters" type="tns:parameterType" minOccurs="0" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="stop" substitutionGroup="tns:setupMethods" type="tns:stopType"/>
	
	<complexType name="stopType">
		<complexContent>
			<extension base="tns:setupMethodsType"/>
		</complexContent>
	</complexType>
	
	<element name="setupCommand" abstract="true" substitutionGroup="tns:atomicCommand" type="tns:setupCommandType"/>
	
	<complexType name="setupCommandType">
		<complexContent>
			<extension base="tns:atomicCommandType"/>
		</complexContent>
	</complexType>
	
	<element name="wait" substitutionGroup="tns:controlCommand" type="tns:waitType"/>
	
	<complexType name="waitType">
		<complexContent>
			<extension base="tns:controlCommandType">
				<attribute name="time" type="long" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="controlCommand" substitutionGroup="tns:atomicCommand" type="tns:controlCommandType" abstract="true"/>
	
	<complexType name="controlCommandType">
		<complexContent>
			<extension base="tns:atomicCommandType"/>
		</complexContent>
	</complexType>
	
	<element name="atomicCommand" abstract="true" substitutionGroup="tns:command" type="tns:atomicCommandType"/>
	
	<complexType name="atomicCommandType">
		<complexContent>
			<extension base="tns:commandType"/>	
		</complexContent>
	</complexType>
	
	<element name="command" abstract="true" type="tns:commandType"/>
	
	<complexType name="commandType"/>

    <element name="script">
    	<complexType>
    		<sequence>
    			<element ref="tns:command" minOccurs="0" maxOccurs="unbounded"/>
    		</sequence>
    	</complexType>
    	<keyref name="instanceVarKeyRef" refer="tns:instanceKey">
			<selector xpath="./*"/>
			<field xpath="@instance"/>
		</keyref>
		<unique name="instanceKey">
			<selector xpath="./tns:instance|tns:instanceGroup"/>
			<field xpath="@varName"/>
		</unique>
    </element>
</schema>

=== mobilis/Emulation/GWTEmulationServer/src/script-utils/XHuntTestScript_multiPlayer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XMLEmulationScript.xsd can also be found on http://mobilis.inf.tu-dresden.de/XMLEmulationScript/XMLEmulationScript.xsd -->
<script xmlns="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mobilis.inf.tu-dresden.de/XMLEmulationScript http://mobilis.inf.tu-dresden.de/XMLEmulationScript.xsd">

	<!-- define application instances -->
	<instance varName="MisterX" appNS="de.tudresden.inf.rn.mobilis.android.xhunt" instanceId="1"/>
	<instanceGroup firstInstanceId="1" appNS="de.tudresden.inf.rn.mobilis.android.xhunt" instanceCount="3" varName="Agents"/>
	
	<!-- start command -->
	<start instance="MisterX" />
	<start instance="Agents" />
	
	<!-- wait -->
	<wait time="10000"/>

	<!-- first MisterX clicks play -->
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Play</string>
		</parameter>
	</appCommand>
	
	<!-- MisterX waits for OpenGamesActivity -->
	<appCommand instance="MisterX" methodName="waitForActivtiy">
		<parameter>
			<string>OpenGamesActivity</string>
		</parameter>
	</appCommand>
	
	<!-- MisterX - Create Game -->
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Create New Game</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="enterText">
		<parameter>
			<string>XHuntTestGame</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Ok</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnText">
		<parameter>
			<string>Dresden</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Create</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="waitForActivity">
		<parameter>
			<string>LobbyActivity</string>
		</parameter>
	</appCommand>
	<wait time="5000"/>
	
	<!-- next Agents click Play and join the game -->
	<appCommand instance="Agents" methodName="clickOnButton">
		<parameter>
			<string>Play</string>
		</parameter>
	</appCommand>
	<appCommand instance="Agents" methodName="waitForActivtiy">
		<parameter>
			<string>OpenGamesActivity</string>
		</parameter>
	</appCommand>
	<appCommand instance="Agents" methodName="clickOnText">
		<parameter>
			<string>XHuntTestGame</string>
		</parameter>
	</appCommand>
	<appCommand instance="Agents" methodName="clickOnText">
		<parameter>
			<string>Join</string>
		</parameter>
	</appCommand>
	<appCommand instance="Agents" methodName="waitForActivity">
		<parameter>
			<string>LobbyActivity</string>
		</parameter>
	</appCommand>
	
	<wait time="5000"/>
	
	<!-- Agents click Ready -->
	<appCommand instance="Agents" methodName="clickOnButton">
		<parameter>
			<string>Ready</string>
		</parameter>
	</appCommand>
	
	<wait time="5000"/>
	
	<!-- MisterX clicks Ready -->
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Ready</string>
		</parameter>
	</appCommand>
	
	<!-- both wait for XHuntMapActivtiy -->
	<appCommand instance="MisterX" methodName="waitForActivity">
		<parameter>
			<string>XHuntMapActivity</string>
		</parameter>
	</appCommand>
	<appCommand instance="Agents" methodName="waitForActivity">
		<parameter>
			<string>XHuntMapActivity</string>
		</parameter>
	</appCommand>
	<wait time="5000"/>
		
	<!-- play 3 rounds -->
	<for times="3">
		<!-- First: MisterX -->
		<appCommand instance="MisterX" methodName="waitForText">
			<parameter>
				<string>New Round</string>
			</parameter>
		</appCommand>
		<appCommand instance="MisterX" methodName="clickOnButton">
			<parameter>
				<string>OK</string>
			</parameter>
		</appCommand>
		<appCommand instance="MisterX" methodName="centerMap"/>
		<!-- setMapZoom is executed only in first round -> implemented on client-side -->
		<!-- int-param => actual zoom-level + #num -->
		<appCommand instance="MisterX" methodName="setMapZoom">
			<parameter>
				<int>1</int>
			</parameter>
		</appCommand>
		<!-- click on a station randomly -->
		<appCommand instance="MisterX" methodName="selectNextStation"/>
		<appCommand instance="MisterX" methodName="clickOnText">
			<parameter>
				<string>Select as next target</string>
			</parameter>
		</appCommand>
		
		<!-- Then the Agents -->
		<appCommand instance="Agents" methodName="waitForText">
			<parameter>
				<string>New Round</string>
			</parameter>
		</appCommand>
		<appCommand instance="Agents" methodName="clickOnButton">
			<parameter>
				<string>OK</string>
			</parameter>
		</appCommand>
		<appCommand instance="Agents" methodName="centerMap"/>
		<!-- setMapZoom is executed only in first round -> implemented on client-side -->
		<!-- int-param => actual zoom-level + #num -->
		<appCommand instance="Agents" methodName="setMapZoom">
			<parameter>
				<int>1</int>
			</parameter>
		</appCommand>
		<!-- click on a station randomly -->
		<appCommand instance="Agents" methodName="selectNextStation"/>
		<appCommand instance="Agents" methodName="clickOnText">
			<parameter>
				<string>Select as next target</string>
			</parameter>
		</appCommand>
	</for>
	
	<!-- now MisterX leaves the game -->
	<appCommand instance="MisterX" methodName="waitForText">
		<parameter>
			<string>New Round</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>OK</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnMenuItem">
		<parameter>
			<string>Quit</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>OK</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="waitForActivity">
		<parameter>
			<string>OpenGamesActivity</string>
		</parameter>
	</appCommand>
	
	<!-- Agents get GameOver-Message, leave game -->
	<appCommand instance="Agents" methodName="waitForText">
		<parameter>
			<string>Game Over</string>
		</parameter>
	</appCommand>
	<appCommand instance="Agents" methodName="clickOnButton">
		<parameter>
			<string>Ok</string>
		</parameter>
	</appCommand>
	
	<stop instance="MisterX"/>
	<stop instance="Agents"/>

</script>

=== mobilis/Emulation/GWTEmulationServer/src/script-utils/XHuntTestScript_singlePlayer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XMLEmulationScript.xsd can also be found on http://mobilis.inf.tu-dresden.de/XMLEmulationScript/XMLEmulationScript.xsd -->
<script xmlns="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mobilis.inf.tu-dresden.de/XMLEmulationScript http://mobilis.inf.tu-dresden.de/XMLEmulationScript.xsd">

	<!-- define application instances -->
	<instance varName="MisterX" appNS="de.tudresden.inf.rn.mobilis.android.xhunt" instanceId="1"/>
	
	<!-- start command -->
	<start instance="MisterX" />
	
	<!-- wait -->
	<wait time="10000"/>

	<!-- first MisterX clicks play -->
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Play</string>
		</parameter>
	</appCommand>
	
	<!-- MisterX waits for OpenGamesActivity -->
	<appCommand instance="MisterX" methodName="waitForActivtiy">
		<parameter>
			<string>OpenGamesActivity</string>
		</parameter>
	</appCommand>
	
	<!-- MisterX - Create Game -->
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Create New Game</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="enterText">
		<parameter>
			<string>XHuntTestGame</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Ok</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnText">
		<parameter>
			<string>Dresden</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Create</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="waitForActivity">
		<parameter>
			<string>LobbyActivity</string>
		</parameter>
	</appCommand>
	<wait time="5000"/>
	
	<!-- MisterX clicks Ready -->
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>Ready</string>
		</parameter>
	</appCommand>
	
	<!-- both wait for XHuntMapActivtiy -->
	<appCommand instance="MisterX" methodName="waitForActivity">
		<parameter>
			<string>XHuntMapActivity</string>
		</parameter>
	</appCommand>
	<wait time="5000"/>
	
<!-- 	<appCommand instance="MisterX" methodName="waitForText">
		<parameter>
			<string>New Round</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>OK</string>
		</parameter>
	</appCommand>
	
	<appCommand instance="MisterX" methodName="centerMap"/>
	<appCommand instance="MisterX" methodName="setMapZoom">
		<parameter>
			<int>1</int>
		</parameter>
	</appCommand> -->
	
	<!-- play 3 rounds -->
	<for times="3">
		<appCommand instance="MisterX" methodName="waitForText">
			<parameter>
				<string>New Round</string>
			</parameter>
		</appCommand>
		<appCommand instance="MisterX" methodName="clickOnButton">
			<parameter>
				<string>OK</string>
			</parameter>
		</appCommand>
		<appCommand instance="MisterX" methodName="centerMap"/>
		<!-- setMapZoom is executed only in first round -> implemented on client-side -->
		<!-- int-param => actual zoom-level + #num -->
		<appCommand instance="MisterX" methodName="setMapZoom">
			<parameter>
				<int>1</int>
			</parameter>
		</appCommand>
		<!-- click on a station randomly -->
		<appCommand instance="MisterX" methodName="selectNextStation"/>
		<appCommand instance="MisterX" methodName="clickOnText">
			<parameter>
				<string>Select as next target</string>
			</parameter>
		</appCommand>
	</for>
	
	<!-- now MisterX leaves the game and closes the app -->
	<appCommand instance="MisterX" methodName="waitForText">
		<parameter>
			<string>New Round</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>OK</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnMenuItem">
		<parameter>
			<string>Quit</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="clickOnButton">
		<parameter>
			<string>OK</string>
		</parameter>
	</appCommand>
	<appCommand instance="MisterX" methodName="waitForActivity">
		<parameter>
			<string>OpenGamesActivity</string>
		</parameter>
	</appCommand>
	
	<stop instance="MisterX"/>

</script>

=== mobilis/Emulation/GWTEmulationServer/src/script-utils/testScript.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XMLEmulationScript.xsd can also be found on http://mobilis.inf.tu-dresden.de/XMLEmulationScript/XMLEmulationScript.xsd -->
<script xmlns="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mobilis.inf.tu-dresden.de/XMLEmulationScript http://mobilis.inf.tu-dresden.de/XMLEmulationScript.xsd">
	<!-- define application instances -->
	<instance varName="doctor" appNS="time.lord" instanceId="1"/>
	<instanceGroup varName="daleks" appNS="evil.race" firstInstanceId="1" instanceCount="20"/>
	<instanceGroup firstInstanceId="21" appNS="evil.race" instanceCount="3" varName="daleks2"/>
	
	<!-- start instances -->
	<start instance="daleks"/>
	<start instance="daleks2"/>
	<start instance="doctor"/>
	
	<!-- run commands -->
	<appCommand instance="daleks" methodName="exterminate"/>
	<for times="20">
		<appCommand instance="doctor" methodName="useScrewdriver"/>
	</for>
	
	<!-- wait 10 seconds -->
	<wait time="10000"/>
	
	<!-- run some more commands -->
	<appCommand instance="doctor" methodName="rescueWorld" async="true">
	    <parameter>
	        <string>tardis</string>
	        <boolean>true</boolean>
	        <int>42</int>
	    </parameter>
	</appCommand>
	<appCommand instance="daleks" methodName="roll">
	    <parameter>
	        <double>42.00</double>
	    </parameter>
	</appCommand>
	<appCommand instance="daleks2" methodName="shout">
		<parameter>
			<string>Exterminate!</string>
			<string>%id%</string>
		</parameter>
	</appCommand>
	
	<!-- stop instances -->
	<stop instance="daleks"/>
	<stop instance="daleks2"/>
	<stop instance="doctor"/>
</script>

=== mobilis/Emulation/GWTEmulationServer/src/script-utils/testScript2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XMLEmulationScript.xsd can also be found on http://mobilis.inf.tu-dresden.de/XMLEmulationScript/XMLEmulationScript.xsd -->
<script xmlns="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mobilis.inf.tu-dresden.de/XMLEmulationScript http://mobilis.inf.tu-dresden.de/XMLEmulationScript.xsd">
	<!-- define application instances -->
	<instance varName="deviceMisterX" appNS="de.tudresden.inf.rn.mobilis.android.xhunt" instanceId="1"/>
	<instance varName="deviceAgent" appNS="de.tudresden.inf.rn.mobilis.android.xhunt" instanceId="2"/>
	
	<!-- start instances -->
	<start instance="deviceMisterX"/>
	<start instance="deviceAgent"/>
	
	<!-- run commands -->
	<appCommand instance="deviceMisterX" methodName="clickOnButton">
		<parameter>
			<string>Play</string>
		</parameter>
	</appCommand>
	<appCommand instance="deviceMisterX" methodName="clickOnButton">
		<parameter>
			<string>Create New Game</string>
		</parameter>
	</appCommand>
	<appCommand instance="deviceMisterX" methodName="enterText">
		<parameter>
			<string>EmulationTest</string>
		</parameter>
	</appCommand>
	<appCommand instance="deviceMisterX" methodName="clickOnButton">
		<parameter>
			<string>Ok</string>
		</parameter>
	</appCommand>
	<appCommand instance="deviceMisterX" methodName="clickOnText">
		<parameter>
			<string>Dresden</string>
		</parameter>
	</appCommand>
	<appCommand instance="deviceMisterX" methodName="clickOnButton">
		<parameter>
			<string>Create</string>
		</parameter>
	</appCommand>
	<!-- wait for MisterX to create the Game -->
	<wait time="15000"/>
	
	<!-- stop instances -->
	<!-- stop instance="daleks"/ -->
	<!-- stop instance="doctor"/ -->
</script>
